<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="inertial_macros.xacro"/>

  <!-- Robot's base properties -->
  <xacro:property name="base_length" value="0.21"/>
  <xacro:property name="base_width" value="0.11"/>
  <xacro:property name="base_height" value="0.035"/>

  <!-- Robot's wheel properties -->
  <xacro:property name="wheel_radius" value="0.0325"/>
  <xacro:property name="wheel_height" value="0.025"/>
  <xacro:property name="wheel_mass" value="0.031"/>

  <!-- Distance between centre of wheel and robot base -->
  <xacro:property name="wheel_zoff" value="0.0125"/>

  <link name="base_footprint"/> 	

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="-0.076 0 ${(wheel_radius + wheel_zoff / 2)}" rpy="0 0 0"/>
  </joint>
	
  <!-- Robot base chasis-->
  <link name="base_link">
      <visual>
        <origin xyz="${base_length/2} 0 ${-wheel_zoff}" rpy="0 0 0"/>
          <geometry>
              <mesh filename="package://demo_description/meshes/robot_chassis.dae" />
          </geometry>
      </visual>
      <collision>
        <origin xyz="${base_length/2} 0 ${-wheel_zoff}" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
      </collision>
      
      <visual>
        <origin xyz="${base_length/2} 0 ${0.05-wheel_zoff}" rpy="0 0 0"/>
          <geometry>
              <mesh filename="package://demo_description/meshes/robot_chassis.dae" />
          </geometry>
      </visual>
      <collision>
        <origin xyz="${base_length/2} 0 ${0.05-wheel_zoff}" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
      </collision>

    <!-- Caster mount -->
      <visual name="caster_mount_visual">
          <origin xyz="0.1915 0 -0.0475" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://demo_description/meshes/caster_mount.dae" />
        </geometry>
      </visual>
      <collision name="caster_mount_collision">
        <origin xyz="0.1915 0 -0.005" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.023" length="0.0125"/>
        </geometry>
      </collision>

      <!-- Raspberry Pi -->
      <visual name="rpi_4_visual">
        <origin xyz="0.164 0 0.0035" rpy="0 0 ${-pi/2}"/>
        <geometry>
          <mesh filename="package://demo_description/meshes/rpi_4.dae"/>
        </geometry>
      </visual>
      <collision name="rpi_4_collision">
        <origin xyz="0.195 0 0.0035" rpy="0 0 ${-pi/2}"/>
        <geometry>
          <box size="0.09 0.06 0.02"/>
        </geometry>
      </collision>

      <!-- Power bank -->
      <visual name="power_bank_visual">
        <origin xyz="0.096 -0.031 -0.02" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://demo_description/meshes/power_bank.dae"/>
        </geometry>
      </visual>
      <collision name="power_bank_collision">
        <origin xyz="0.094 -0.031 -0.02" rpy="0 0 ${pi/2}"/>
        <geometry>
          <box size="0.094 0.062 0.02"/>
        </geometry>
      </collision>

      <!-- Rplidar base -->
      <visual name="rplidar_base_visual">
        <origin xyz="0.175 0 0.05" rpy="0 0 ${pi}"/>
          <geometry>
            <mesh filename="package://demo_description/meshes/rplidar_base.dae"/>
          </geometry>
        </visual>
      <collision name="rplidar_base_collision">
        <origin xyz="0.175 0 0.05" rpy="0 0 ${pi}"/>
        <geometry>
          <box size="0.11 0.072 0.035"/>
        </geometry>
      </collision>

    <xacro:box_inertia mass="1.864" length="${base_length}" width="${base_width}" height="${base_height}">
      <origin xyz="0.105 0 0.0175" rpy="0 0 0"/>
    </xacro:box_inertia>
  </link>

  <!-- Left Wheel -->
  <link name="left_wheel">
    <visual>
        <geometry>
          <mesh filename="package://demo_description/meshes/left_wheel.dae" />
        </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.0065" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <xacro:cylinder_inertia mass="${wheel_mass}" length="${wheel_height}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:cylinder_inertia>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0.077 0.055 -${wheel_zoff}" rpy="${pi/2} 0 ${pi}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Right Wheel -->
  <link name="right_wheel">
    <visual>
      <origin xyz="0 0 -0.009" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://demo_description/meshes/right_wheel.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <xacro:cylinder_inertia mass="${wheel_mass}" length="${wheel_height}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:cylinder_inertia>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0.077 -0.055 -${wheel_zoff}" rpy="${pi/2} 0 ${-pi}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Caster wheel -->
  <link name="caster_wheel">
    <visual>
      <geometry>
        <mesh filename="package://demo_description/meshes/caster_wheel.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 -0.001" rpy="0 0 ${pi/2}"/>
      <geometry>
        <sphere radius="0.015"/>
      </geometry>
    </collision>

    <xacro:sphere_inertia mass="0.033" radius="0.025">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:sphere_inertia>
  </link>

  <joint name="caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="0.182 0 -0.031" rpy="0 0 ${-pi/2}"/>
  </joint>

  <gazebo reference="caster_wheel">
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
  </gazebo>

</robot>
